"""What has to be true before six public repos exist, checked without a network.

Every failure here is one a reader meets rather than the person who caused it. A repo is
public, is permanent enough that people link to it, and is between one and four gigabytes of
someone else's bandwidth before any of its claims can be checked. So the tests are about the
gap between the label on a directory and the checkpoint inside it:

* a card that names a repo id the push does not use, which is a 404 reached only after the
  reader has decided to trust the numbers above it;
* a directory that is not the model the panel scored -- the failure this campaign has
  already paid for once, when four Mistral arms wrote into a Qwen directory;
* a directory the publish pass did not write, which the container can prove -- unlike a
  swap between two quantized arms, which it cannot, because the recipe arms and the
  DynQuant arms come out of the same exporter into the same container;
* a token on the command line, which is a token in shell history and in `ps`.

Nothing here touches the Hub. `upload` is the only function that does, and it is the only
one not exercised: what these cover is everything that decides whether it is called.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
from test_model_cards import FINETUNE, _built
from test_panel_table import REPO_ROOT, SCRIPT, _load, _write_panel

PUSHER = REPO_ROOT / "experiments" / "phase4" / "push_to_hub.py"

#: The merge every published directory is checked against. Two fields, because those are the
#: two the check compares -- a fuller config would suggest the check reads more than it does.
BASE = {"architectures": ["MistralForCausalLM"], "vocab_size": 32768}

PREFIX = "anorg/mistral-7b-instruct-v0.3-text2sql"

RECIPE_KINDS = ("gptq", "awq", "rtn")


@pytest.fixture(scope="module")
def pusher() -> Any:
    return _load("_dq_push_to_hub", PUSHER)


@pytest.fixture(scope="module")
def table_mod() -> Any:
    return _load("_dq_panel_table_for_push", SCRIPT)


def _dir(path: Path, config: dict[str, Any]) -> Path:
    """A published arm: a config, a weight file and nothing else that matters."""
    path.mkdir(parents=True, exist_ok=True)
    (path / "config.json").write_text(json.dumps(config), encoding="utf-8")
    (path / "model.safetensors").write_bytes(b"0" * 1024)
    return path


def _quant_config(kind: str, anchor: int) -> dict[str, Any]:
    """What each kind of second pass leaves in `config.json`.

    Identical `quant_method` for both, because that is the truth: every arm in this panel is
    written by DynQuant's exporter and the recipe arms carry their codes into its container.
    The widths differ -- a recipe export is uniform at its anchor, an allocation is not --
    and that difference is reported to a human rather than enforced, so the fixture carries
    it for the reporting test and nothing asserts on it.
    """
    bits = [anchor] if kind in RECIPE_KINDS else sorted({anchor, anchor - 1, 8})
    return {
        "quant_method": "dynquant",
        "modules": {f"model.layers.0.m{i}": {"bits": b} for i, b in enumerate(bits)},
    }


def _panel(tmp_path: Path, table_mod: Any) -> tuple[dict[str, Any], Path, dict[str, Any]]:
    """A scored panel, a directory per quantized arm, and a fine-tune naming its merge."""
    table, _ = _built(table_mod, _write_panel(tmp_path / "arms"))
    published = tmp_path / "published"
    for row in table["arms"]:
        if row.get("kind") in (*RECIPE_KINDS, "dq") and row.get("accuracy") is not None:
            _dir(
                published / row["label"],
                {**BASE, "quantization_config": _quant_config(row["kind"], row["anchor"])},
            )
    merged = _dir(tmp_path / "merged", dict(BASE))
    return table, published, {**FINETUNE, "output": str(merged)}


def _config_of(path: Path) -> dict[str, Any]:
    return json.loads((path / "config.json").read_text(encoding="utf-8"))


def _rewrite(path: Path, config: dict[str, Any]) -> None:
    (path / "config.json").write_text(json.dumps(config), encoding="utf-8")


def test_the_repo_a_card_tells_you_to_load_is_the_repo_it_was_pushed_to(
    pusher: Any, table_mod: Any, tmp_path: Path
) -> None:
    """The id in the usage snippet and the id in the upload come from one call to `slug`.

    A card generated under one `--repo-prefix` and pushed under another is not a broken
    build -- it renders, it uploads, and it is wrong only in the line a reader copies. So
    the card is generated by the pusher, from the prefix the pusher is using, and this is
    the test that says the two are the same string.

    Turns red when: the id is rebuilt anywhere in the push path instead of coming from
    `model_cards.slug`, or the card is read off disk rather than generated.
    """
    import model_cards

    table, published, finetune = _panel(tmp_path, table_mod)
    labels = model_cards.publishable(table, include_ceiling=True)
    pushes = pusher.sources(table, finetune, published, labels, PREFIX)

    assert pushes, "the fixture panel has scored arms"
    for push in pushes:
        card = model_cards.card(table, push.label, finetune, repo_prefix=PREFIX)
        assert push.repo in card, f"{push.label}'s card never names {push.repo}"
        assert push.repo.startswith(f"{PREFIX}-")


def test_the_ceiling_is_taken_from_the_manifest_and_not_from_the_publish_directory(
    pusher: Any, table_mod: Any, tmp_path: Path
) -> None:
    """The merged fine-tune is where the trainer put it, which no other arm's path predicts.

    `publish_panel.py` writes a directory per quantized arm and none for the ceiling,
    because the ceiling was never quantized. Resolving it under `--published` anyway would
    fail the existence check on a good run; rebuilding a path from a run root would find
    whatever else is there, which is how four Mistral arms once picked up a Qwen tokenizer.

    Turns red when: the ceiling's source stops coming from the manifest's `output`.
    """
    table, published, finetune = _panel(tmp_path, table_mod)
    ceiling = next(r["label"] for r in table["arms"] if r.get("kind") == "ceiling")
    push = pusher.sources(table, finetune, published, [ceiling], PREFIX)[0]

    assert push.source == Path(finetune["output"])
    assert push.repo.endswith("-bf16")


def test_a_directory_that_is_not_this_checkpoint_stops_the_push(
    pusher: Any, table_mod: Any, tmp_path: Path
) -> None:
    """Cross-contamination between run directories, caught against the merge itself.

    Every arm is one checkpoint quantized several ways, so `architectures` and `vocab_size`
    are the same in all of them or one is a different model. A mismatched vocabulary is not
    subtle downstream -- the ids go out of range and it asserts device-side -- but by then
    the repo is public.

    Turns red when: the published directories stop being checked against the merge.
    """
    table, published, finetune = _panel(tmp_path, table_mod)
    label = next(p.name for p in published.iterdir())
    _rewrite(published / label, {**_config_of(published / label), "vocab_size": 151936})

    pushes = pusher.sources(table, finetune, published, [label], PREFIX)
    problems = pusher.check(pushes, Path(finetune["output"]))
    assert len(problems) == 1, problems
    assert "151936" in problems[0] and "32768" in problems[0]


def test_a_directory_the_publish_pass_did_not_write_is_refused(
    pusher: Any, table_mod: Any, tmp_path: Path
) -> None:
    """Every arm here is written by DynQuant's exporter, so anything else is not this pass.

    The recipe arms carry their codes into DynQuant's container and load through its
    quantizer, which is why the check is "written by the exporter" and not "written by the
    method the label names". A directory carrying `compressed-tensors` is llm-compressor's
    own output, one step short of the export the panel scored, and it would not load the way
    its card says it does.

    What this deliberately does not cover: `gptq_4b` holding the DynQuant export. Both are
    the same container with the same `quant_method`, differing only in widths the allocator
    chose, and a uniform allocation is legal when the budget stops binding -- so the widths
    are printed for a human rather than refused on. Asserting that gap here rather than
    leaving it implied, because a test file is also where somebody looks to find out what is
    covered.

    Turns red when: the container check is dropped, or a second `quant_method` is quietly
    accepted.
    """
    table, published, finetune = _panel(tmp_path, table_mod)
    label = next(p.name for p in published.iterdir())
    config = _config_of(published / label)
    config["quantization_config"] = {"quant_method": "compressed-tensors", "config_groups": {}}
    _rewrite(published / label, config)

    pushes = pusher.sources(table, finetune, published, [label], PREFIX)
    problems = pusher.check(pushes, Path(finetune["output"]))
    assert len(problems) == 1, problems
    assert "compressed-tensors" in problems[0]


def test_the_plan_prints_how_many_widths_each_map_carries(
    pusher: Any, table_mod: Any, tmp_path: Path
) -> None:
    """The one line separating a uniform recipe export from an allocation, in front of a human.

    It is not a guard and must not become one, so what this covers is that the number is
    read off the map the exporter wrote -- a recipe arm uniform at its anchor, a DynQuant
    arm carrying several widths -- and reaches the plan rather than being computed and
    dropped.

    Turns red when: the plan stops distinguishing the two, which is what would make a swap
    between quantized arms invisible at the moment somebody is deciding to publish them.
    """
    _, published, _ = _panel(tmp_path, table_mod)
    recipe = published / "gptq_4b"
    allocated = published / "dq_4b"

    assert pusher.widths(recipe) == "1x{4}b", "a recipe export is uniform at its anchor"
    assert pusher.widths(allocated) == "3x{3,4,8}b", "an allocation spends its budget unevenly"
    assert pusher.widths(Path(_dir(tmp_path / "bare", dict(BASE)))) == "unquantized"


def test_an_unquantized_ceiling_carrying_a_quantization_config_is_refused(
    pusher: Any, table_mod: Any, tmp_path: Path
) -> None:
    """The card says this one was never quantized, above weights that say otherwise.

    Turns red when: the ceiling stops being checked for the absence its own card asserts.
    """
    table, published, finetune = _panel(tmp_path, table_mod)
    merged = Path(finetune["output"])
    _rewrite(merged, {**BASE, "quantization_config": _quant_config("dq", 4)})
    ceiling = next(r["label"] for r in table["arms"] if r.get("kind") == "ceiling")

    pushes = pusher.sources(table, finetune, published, [ceiling], PREFIX)
    problems = pusher.check(pushes, merged)
    assert any("unquantized" in problem for problem in problems), problems


def test_a_token_passed_as_an_argument_is_refused_rather_than_used(
    pusher: Any, tmp_path: Path
) -> None:
    """By the time this runs the token is already in shell history and was already in `ps`.

    Refusing does not undo that, which is why the message says to revoke it rather than
    just declining. Using it would leave a working credential in two logs with nobody told.
    The refusal comes before the table is read, so a token cannot be spent on a run that was
    going to fail anyway.

    Turns red when: a `--token` flag is added, or the check stops running first.
    """
    secret = "hf_" + "a" * 34
    argv = [
        "--table",
        str(tmp_path / "table.json"),
        "--finetune",
        str(tmp_path / "ft.json"),
        "--published",
        str(tmp_path),
        "--repo-prefix",
        PREFIX,
        "--token",
        secret,
    ]
    with pytest.raises(SystemExit) as caught:
        pusher.main(argv)
    assert "revoke" in str(caught.value)
    assert secret not in str(caught.value), "the refusal must not reprint the token"
